name: islamic_companion_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Prayer times + formatting
  adhan: ^2.0.0
  intl: ^0.19.0

  # Location (works on web with browser permission prompt)
  geolocator: ^13.0.4

  # Local storage (method/madhab preferences)
  shared_preferences: ^2.5.4
  flutter_compass: ^0.8.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true